name: bakery CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: create aws properties file
      run: |
        touch src/main/resources/application-aws.properties
        echo "${{ secrets.ENV_AWS }}" >> src/main/resources/application-aws.properties

    - name: create oauth properties file
      run: |
        touch src/main/resources/application-oauth.properties
        echo "${{ secrets.ENV_OAUTH }}" >> src/main/resources/application-oauth.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build
